const $=id=>document.getElementById(id), N=id=>Number($(id)?.value||0)||0, M=n=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const S={db:[],history:[],v:{},c:{},margin:0,roi:15,selected:null};
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='result')result();if(id==='history')history();}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function read(){S.v={brand:$('brand').value,model:$('model').value,year:N('year'),trim:$('trim').value,traction:$('traction').value,country:$('country').value,mileage:N('mileage'),zipOrigin:$('zipOrigin').value,zipDest:$('zipDest').value,platform:$('platform').value,lot:$('lot').value,tableValue:S.selected?.value||0};S.c={bid:N('bid'),auctionFee:N('auctionFee'),inland:N('inland'),docs:N('docs'),repairMiami:N('repairMiami'),broker:N('broker'),honorarios:N('honorarios'),freight:N('freight'),dispatch:N('dispatch'),fx:N('fx')||60,repairRD:N('repairRD'),sale:N('sale')};}
function ensureTaxInputs(){
  if(!$('insuranceDga')){const i=document.createElement('input');i.type='hidden';i.id='insuranceDga';i.value='0';document.body.appendChild(i)}
  if(!$('dgaAdditional')){const i=document.createElement('input');i.type='hidden';i.id='dgaAdditional';i.value='0';document.body.appendChild(i)}
  if(!$('tariffMode')){const s=document.createElement('select');s.id='tariffMode';s.innerHTML='<option value="0.10" selected>Sin Tratado (10%)</option><option value="0">Con Tratado Preferencial (0%)</option>';s.style.display='none';document.body.appendChild(s)}
}
ensureTaxInputs();

function auctionFee(bid,platform,type='online'){bid=Number(bid)||0;let buyer=0,internet=0,gate=platform==='IAAI'?95:79,env=platform==='IAAI'?15:0,title=platform==='IAAI'?20:0;if(platform==='IAAI'){if(bid<=49.99)buyer=5;else if(bid<=99.99)buyer=10;else if(bid<=199.99)buyer=40;else if(bid<=399.99)buyer=75;else if(bid<=499.99)buyer=100;else if(bid<=599.99)buyer=130;else if(bid<=699.99)buyer=155;else if(bid<=799.99)buyer=180;else if(bid<=899.99)buyer=205;else if(bid<=999.99)buyer=230;else if(bid<=1199.99)buyer=260;else if(bid<=1299.99)buyer=290;else if(bid<=1499.99)buyer=330;else if(bid<=1999.99)buyer=415;else if(bid<=2499.99)buyer=465;else if(bid<=2999.99)buyer=515;else if(bid<=3499.99)buyer=565;else if(bid<=3999.99)buyer=615;else if(bid<=4499.99)buyer=665;else if(bid<=4999.99)buyer=715;else if(bid<=6999.99)buyer=770;else if(bid<=7499.99)buyer=820;else buyer=bid*.085;if(bid<=99.99)internet=0;else if(bid<=499.99)internet=type==='live'?45:35;else if(bid<=999.99)internet=type==='live'?65:55;else if(bid<=1499.99)internet=type==='live'?85:75;else if(bid<=1999.99)internet=type==='live'?105:95;else if(bid<=2999.99)internet=type==='live'?120:110;else if(bid<=4999.99)internet=type==='live'?135:125;else internet=type==='live'?140:129;}else{if(bid<=49.99)buyer=5;else if(bid<=99.99)buyer=15;else if(bid<=399.99)buyer=60;else if(bid<=499.99)buyer=85;else if(bid<=599.99)buyer=115;else if(bid<=699.99)buyer=140;else if(bid<=799.99)buyer=165;else if(bid<=899.99)buyer=190;else if(bid<=999.99)buyer=215;else if(bid<=1199.99)buyer=245;else if(bid<=1299.99)buyer=275;else if(bid<=1399.99)buyer=295;else if(bid<=1499.99)buyer=325;else if(bid<=1599.99)buyer=350;else if(bid<=1699.99)buyer=370;else if(bid<=1799.99)buyer=390;else if(bid<=1999.99)buyer=425;else if(bid<=2499.99)buyer=475;else if(bid<=2999.99)buyer=525;else if(bid<=3499.99)buyer=575;else if(bid<=3999.99)buyer=625;else if(bid<=4499.99)buyer=675;else if(bid<=4999.99)buyer=725;else if(bid<=6999.99)buyer=775;else if(bid<=7499.99)buyer=825;else if(bid<=9999.99)buyer=875;else buyer=bid*.085;if(bid<=99.99)internet=0;else if(bid<=499.99)internet=type==='live'?49:39;else if(bid<=999.99)internet=type==='live'?69:59;else if(bid<=1499.99)internet=type==='live'?89:79;else if(bid<=1999.99)internet=type==='live'?99:89;else if(bid<=3999.99)internet=type==='live'?119:109;else if(bid<=5999.99)internet=type==='live'?129:119;else internet=type==='live'?149:139;}return buyer+internet+gate+env+title;}
function customsCalc(){
  const table=S.selected?.value||0, fx=N('fx')||60.60, freight=N('freight')||910, insurance=N('insuranceDga');
  const seguro=Number.isFinite(insurance)&&insurance>=0?insurance:0;
  const cifUsd=table+freight+seguro, cifRds=cifUsd*fx;
  const p=Number($('tariffMode')?.value ?? 0.10);
  const additional=N('dgaAdditional');
  const arancel=cifRds*p, itbis=(cifRds+arancel)*0.18, subAduana=arancel+itbis;
  const fixedDga=8912.44+258.26+5713.61;
  const dgaSin=subAduana+fixedDga+additional;
  const placaBase=cifRds*0.17, co2=cifRds*0.02, placa=placaBase+co2+3000;
  return{table,insurance:seguro,cifUsd,cifRds,p,arancel,itbis,subAduana,additional,fixedDga,dgaSin,placaBase,co2,placa,total:dgaSin+placa};
}
function calc(){read();let c=S.c,t=customsCalc(),fees=auctionFee(c.bid,S.v.platform||'Copart',$('auctionType')?.value||'online');$('auctionFee').value=fees;c.auctionFee=fees;let fob=c.bid+fees+c.inland+c.docs+c.repairMiami+c.broker+c.honorarios,dispatchTotal=fob+c.freight+c.dispatch+t.dgaSin/c.fx,landed=dispatchTotal+t.placa/c.fx+c.repairRD/c.fx;return{fob,dispatchTotal,landed,fees,t};}
function live(){let x=calc();$('fob').textContent=M(x.fob);$('dispatchOut').textContent=M(x.dispatchTotal);$('landed').textContent=M(x.landed);renderTax(x.t);if($('customs'))$('customs').value=Number(x.t.dgaSin||0).toFixed(2);if($('plateCalc'))$('plateCalc').value=Number(x.t.placa||0).toFixed(2);if($('taxesTotalCalc'))$('taxesTotalCalc').value=Number(x.t.total||0).toFixed(2);if($('taxCostSummary'))$('taxCostSummary').textContent='RD$ '+Number(x.t.total||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});}
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',live));document.querySelectorAll('select').forEach(e=>e.addEventListener('change',live));
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim()};function spec(s){let o={};String(s||'').split('||').forEach(p=>{let a=p.split(':');if(a.length>1)o[norm(a[0])]=a.slice(1).join(':').trim()});return o};function te(a,b){a=norm(a).replace(/[^A-Z0-9]/g,'');b=norm(b).replace(/[^A-Z0-9]/g,'');let e=x=>['AWD','4WD','4X4'].includes(x)?'AWD':(['FWD','RWD','4X2','2WD'].includes(x)?x:x);return e(a)===e(b)}
function matches(){read();return S.db.filter(r=>norm(r.Marca)===norm(S.v.brand)&&norm(r.Modelo)===norm(S.v.model)&&Number(r.Año)===S.v.year).map(r=>{let p=spec(r.Especificacion),score=(S.v.trim&&norm(p.SERIE||'').includes(norm(S.v.trim))?50:0)+(S.v.traction&&te(S.v.traction,p.TRACCION)?35:0)+(S.v.country&&norm(S.v.country)===norm(r.Pais)?10:0);return{r,p,score}}).sort((a,b)=>b.score-a.score)}
function applyMatch(){let a=matches();if(!a.length){$('match').textContent='Sin coincidencia segura';$('matchbox').textContent='No se encontró coincidencia exacta por marca + modelo + año. No se cambia el año automáticamente.';return}let x=a[0];showRecord(x.r,x.p);}
function csv(t){let lines=t.split(/\r?\n/),h=lines.shift().split(','),out=[];for(let l of lines){let v=[],q=false,c='';for(let ch of l){if(ch==='"')q=!q;else if(ch===','&&!q){v.push(c);c=''}else c+=ch}v.push(c);let o={};h.forEach((k,i)=>o[k.trim()]=String(v[i]??'').replace(/^"|"$/g,''));if(o.Marca)out.push(o)}return out}
async function db(){try{let r=await fetch(encodeURI('Base de Datos Valores Vehiculos 2026 - 2027.csv'));S.db=csv(await r.text());$('dbStatus').textContent=S.db.length.toLocaleString()+' registros';renderDB();fill('selBrand',[...new Set(S.db.map(r=>r.Marca).filter(Boolean))].sort(),'Selecciona marca');}catch(e){$('dbStatus').textContent='Abrir desde servidor/GitHub Pages';}}
function renderDB(){let q=norm($('dbSearch').value),a=S.db.filter(r=>[r.Marca,r.Modelo,r.Año,r.Especificacion,r.Pais].some(x=>norm(x).includes(q))).slice(0,40);$('dbResults').innerHTML=a.map(r=>{let p=spec(r.Especificacion);return '<div class="dbitem"><div><b>'+r.Marca+' '+r.Modelo+' '+r.Año+'</b><br><span>'+(p.SERIE||'')+' · '+(p.TRACCION||'')+' · '+(r.Pais||'')+'</span></div><b>'+r.Valor+'</b></div>'}).join('')||'<p>Sin resultados.</p>'}$('dbSearch').oninput=renderDB;
function fill(id,items,placeholder,disabled=false){const el=$(id);el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option>${String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;')}</option>`).join('');el.disabled=disabled||!items.length}
function models(b){return [...new Set(S.db.filter(r=>norm(r.Marca)===norm(b)).map(r=>r.Modelo))].sort()};function years(b,m){return [...new Set(S.db.filter(r=>norm(r.Marca)===norm(b)&&norm(r.Modelo)===norm(m)).map(r=>r.Año))].sort((a,b)=>b-a)};function records(b,m,y){return S.db.filter(r=>norm(r.Marca)===norm(b)&&norm(r.Modelo)===norm(m)&&String(r.Año)===String(y))}
function showRecord(r,p=spec(r.Especificacion)){const value=Number(String(r.Valor||'').replace(/[^0-9.-]/g,''))||0;S.selected={...r,...p,value,country:r.Pais||'',traction:p.TRACCION||''};$('selCountry').innerHTML=`<option>${r.Pais||'—'}</option>`;$('selTraction').innerHTML=`<option>${p.TRACCION||'—'}</option>`;$('selCountry').disabled=true;$('selTraction').disabled=true;const specs=[['Tipo',r['Tipo Vehiculo']||'—'],['Serie',p.SERIE||'—'],['Combustible',p.COMBUSTIBLE||'—'],['Cilindros',p.CILINDROS||'—'],['CC',p.CC||'—'],['Pasajeros',p.PASAJEROS||'—'],['Puertas',p.PUERTAS||'—'],['Tracción',p.TRACCION||'—'],['Cabinas',p.CABINAS||'—'],['Carga',p.PESODECARGA||'—'],['Ejes',p.EJES||'—'],['Valor Tabla Aduanas',M(value)]];$('vehicleLoaded').classList.remove('muted');$('vehicleLoaded').innerHTML=`<strong>${r.Marca} ${r.Modelo} ${r.Año}</strong><div class="avm-specs">${specs.map(s=>`<div class="avm-spec"><small>${s[0]}</small><b>${s[1]}</b></div>`).join('')}</div>`;$('brand').value=r.Marca||'';$('model').value=r.Modelo||'';$('year').value=r.Año||'';$('trim').value=p.SERIE||'';$('traction').value=p.TRACCION||'';$('country').value=r.Pais||'';$('match').textContent='Coincidencia encontrada';$('matchbox').innerHTML=`<b>${r.Marca} ${r.Modelo} ${r.Año}</b> · ${(p.SERIE||'')} · ${(p.TRACCION||'')} · Valor Tabla Aduanas ${M(value)}`;$('nextCosts').disabled=false;if($('costPlatform'))$('costPlatform').value=$('platform').value;window.AVM_SELECTED_VEHICLE=S.selected;window.dispatchEvent(new CustomEvent('avm:vehicleReady',{detail:S.selected}));live();}
function chooseFromSelectors(){const b=$('selBrand').value,m=$('selModel').value,y=$('selYear').value;if(!b||!m||!y)return;const rs=records(b,m,y);$('selSeries').innerHTML=`<option value="">Selecciona registro exacto</option>`+rs.map((r,i)=>`<option value="${i}">${(spec(r.Especificacion).SERIE||'Sin serie')} · ${r.Pais||'—'} · ${(spec(r.Especificacion).TRACCION||'—')} · ${(spec(r.Especificacion).CILINDROS||'—')} cyl</option>`).join('');$('selSeries').disabled=!rs.length;$('selCountry').innerHTML='<option>—</option>';$('selTraction').innerHTML='<option>—</option>';}
function chooseSeries(){const rs=records($('selBrand').value,$('selModel').value,$('selYear').value),r=rs[Number($('selSeries').value)];if(r)showRecord(r)}
function scoreSearch(r,q){const tokens=norm(q).split(/\s+/).filter(x=>x.length>1),hay=norm([r.Marca,r.Modelo,spec(r.Especificacion).SERIE,r.Año,r.Pais,spec(r.Especificacion).TRACCION,spec(r.Especificacion).COMBUSTIBLE,r['Tipo Vehiculo']].join(' '));let s=0;tokens.forEach(t=>{if(hay.includes(t))s++});if(norm(r.Marca)&&norm(q).includes(norm(r.Marca)))s+=5;if(norm(r.Modelo)&&norm(q).includes(norm(r.Modelo)))s+=5;if(String(r.Año)&&norm(q).includes(String(r.Año)))s+=4;return s}
function search(q){if(!q.trim())return[];return S.db.map(r=>({r,s:scoreSearch(r,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,15).map(x=>x.r)}
function renderResults(){const q=$('vehicleSearch').value,rs=search(q);$('vehicleSearchResults').innerHTML=rs.map((r,i)=>{let p=spec(r.Especificacion);return `<div class="avm-search-result" data-i="${i}"><div><b>${r.Marca} ${r.Modelo} ${r.Año}</b><br><small>${p.SERIE||'Sin serie'} · ${p.TRACCION||'—'} · ${r.Pais||'—'}</small></div><strong>${M(Number(String(r.Valor||'').replace(/[^0-9.-]/g,''))||0)}</strong></div>`}).join('');$('vehicleSearchResults').querySelectorAll('.avm-search-result').forEach((el,i)=>el.onclick=()=>selectResult(rs[i]));}
function selectResult(r){fill('selModel',models(r.Marca),'Selecciona modelo');$('selBrand').value=r.Marca;$('selModel').value=r.Modelo;fill('selYear',years(r.Marca,r.Modelo),'Selecciona año');$('selYear').value=r.Año;chooseFromSelectors();const rs=records(r.Marca,r.Modelo,r.Año),idx=rs.indexOf(r);$('selSeries').value=String(idx);chooseSeries();$('vehicleSearch').value=`${r.Marca} ${r.Modelo} ${spec(r.Especificacion).SERIE||''} ${r.Año} ${spec(r.Especificacion).TRACCION||''}`.replace(/\s+/g,' ').trim();$('vehicleSearchResults').innerHTML='';}
$('selBrand').onchange=()=>{fill('selModel',models($('selBrand').value),'Selecciona modelo');fill('selYear',[],'Selecciona modelo',true);fill('selSeries',[],'Selecciona año',true)};$('selModel').onchange=()=>{fill('selYear',years($('selBrand').value,$('selModel').value),'Selecciona año');fill('selSeries',[],'Selecciona año',true)};$('selYear').onchange=chooseFromSelectors;$('selSeries').onchange=chooseSeries;$('vehicleSearch').oninput=()=>{clearTimeout(window._vehicleSearchTimer);window._vehicleSearchTimer=setTimeout(renderResults,100)};
function renderTax(t){
  const card=$('avmTaxCard'); if(!card)return;
  if(!S.selected){card.hidden=true;return;}
  card.hidden=false;
  const rd=n=>'RD$ '+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  const rows=[['Valor Tabla Aduanas',M(t.table)],['Flete a DGA',M(N('freight')||910)],['Seguro DGA',M(t.insurance)],['CIF aduanal',M(t.cifUsd)],['Arancel '+(t.p*100).toFixed(0)+'%',rd(t.arancel)],['ITBIS 18%',rd(t.itbis)],['Cargos fijos DGA',rd(t.fixedDga)],['Gastos adicionales DGA',rd(t.additional)],['Primera placa 17%',rd(t.placaBase)],['CO2 2% + Marbete',rd(t.co2+3000)]];
  $('taxRows').innerHTML=rows.map(r=>`<div class="tax-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('');
  $('taxDga').textContent=rd(t.dgaSin); $('taxPlate').textContent=rd(t.placa); $('taxTotal').textContent=rd(t.total);
  $('taxStatus').textContent='✓ Cálculo activo';
  $('customs').value=t.dgaSin;
}

function profitabilityAtBid(bid){const c={...S.c,bid};const fee=auctionFee(bid,S.v.platform||'Copart',$('auctionType')?.value||'online');const t=customsCalc(),fob=bid+fee+c.inland+c.docs+c.repairMiami+c.broker+c.honorarios,total=fob+c.freight+c.dispatch+t.dgaSin/c.fx+t.placa/c.fx+c.repairRD/c.fx,sale=N('sale'),profit=sale-total,roi=total?profit/total*100:0;return{bid,fee,fob,total,profit,roi,t}}
function maxBid(){const sale=N('sale');if(!sale||!S.selected)return 0;let lo=0,hi=Math.max(sale,50000);for(let i=0;i<60;i++){const mid=(lo+hi)/2,r=profitabilityAtBid(mid);if(r.profit>=S.margin&&r.roi>=S.roi)lo=mid;else hi=mid;}return lo}
function result(){const x=calc(),sale=N('sale'),r=profitabilityAtBid(N('bid')),max=maxBid(),ideal=max*.93,risk=max*.98;$('auctionFee').value=r.fee;$('ideal').textContent=M(ideal);$('max').textContent=M(max);$('risk').textContent=M(risk);$('title').textContent=(S.v.brand+' '+S.v.model+' '+S.v.year+' '+S.v.trim).replace(/\s+/g,' ').trim()||'Vehículo';$('meta').textContent=(S.v.traction||'—')+' · '+(S.v.platform||'—')+' · '+(S.v.mileage||0).toLocaleString()+' mi';$('margin').textContent=M(r.profit);$('roi').textContent=r.roi.toFixed(1)+'%';const decision=!sale?'Introduce precio de venta para evaluar':r.profit>=S.margin&&r.roi>=S.roi?'🟢 OPERACIÓN RENTABLE':'🔴 NO RENTABLE CON ESTA PUJA';$('decision').innerHTML=`<b>${decision}</b><br><small>Objetivo configurado: ${M(S.margin)} mínimo y ${S.roi}% ROI.</small>`;let rows=[['Puja',r.bid],['Auction Fee',r.fee],['Inland',S.c.inland],['Documentación',S.c.docs],['Reparación Miami',S.c.repairMiami],['Broker',S.c.broker],['Honorarios',S.c.honorarios],['Flete',S.c.freight],['Despacho RD',S.c.dispatch],['DGA sin placa',r.t.dgaSin/S.c.fx],['Placa',r.t.placa/S.c.fx],['Landed',r.total]];$('rows').innerHTML=rows.map(q=>`<div class="row"><span>${q[0]}</span><b>${M(q[1])}</b></div>`).join('');renderTax(r.t)}
$('nextCosts').onclick=()=>{page('costs');live()};$('nextResult').onclick=()=>{live();page('result')};$('sale').oninput=result;$('platform').onchange=()=>{if($('costPlatform'))if($('costPlatform'))$('costPlatform').value=$('platform').value;live()};if($('auctionType'))$('auctionType').onchange=live;$('bid').oninput=()=>{$('market').value=$('bid').value;live()};
function history(){let a=S.history;$('historyList').innerHTML=a.length?a.map(x=>'<div class="dbitem"><div><b>'+x.v.brand+' '+x.v.model+' '+x.v.year+'</b><br><span>'+x.date+'</span></div><b>'+x.max+'</b></div>').join(''):'Aún no hay operaciones.'}
$('save').onclick=()=>{read();result();S.history.unshift({date:new Date().toLocaleString(),v:{...S.v},max:$('max').textContent});localStorage.setItem('avmHistory',JSON.stringify(S.history));page('history')};$('new').onclick=()=>location.reload();$('defaults').onclick=()=>{['bid','auctionFee','inland'].forEach(x=>$(x).value=0);$('docs').value=675;$('repairMiami').value=950;$('broker').value=250;$('honorarios').value=0;$('freight').value=910;$('dispatch').value=465;$('fx').value=60;$('repairRD').value=0;live()};$('saveSettings').onclick=()=>{let v={broker:N('setBroker'),docs:N('setDocs'),repair:N('setRepair'),freight:N('setFreight'),dispatch:N('setDispatch'),fx:N('setFx'),margin:N('setMargin'),roi:N('setROI'),zip:$('setZip').value};S.margin=v.margin;S.roi=v.roi;$('broker').value=v.broker;$('docs').value=v.docs;$('repairMiami').value=v.repair;$('freight').value=v.freight;$('dispatch').value=v.dispatch;$('fx').value=v.fx;$('zipDest').value=v.zip;localStorage.setItem('avmSettings',JSON.stringify(v));live()};
$('analyze').onclick=()=>{let q=$('quick').value.toUpperCase(),y=q.match(/20\d{2}/),z=q.match(/\b\d{5}\b/g),p=q.match(/(?:COMPRA|PUJA|BID)\s*\$?\s*([\d,.]+)/i);if(y)$('year').value=y[0];if(z)$('zipOrigin').value=z[0];if(p)$('bid').value=p[1].replace(/,/g,'');['AWD','FWD','4WD','4X4','RWD','4X2'].forEach(t=>{if(q.includes(t))$('traction').value=t});['TOYOTA','HYUNDAI','KIA','HONDA','MAZDA','FORD','CHEVROLET','JEEP','ACURA','NISSAN','LEXUS'].forEach(b=>{if(q.includes(b))$('brand').value=b[0]+b.slice(1).toLowerCase()});['RAV4','TUCSON','SPORTAGE','CRV','CX-5','SANTA FE','HIGHLANDER','MDX','SILVERADO','MUSTANG'].forEach(m=>{if(q.includes(m))$('model').value=m});applyMatch();page('vehicle')};$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('avmTheme',document.body.classList.contains('dark')?'dark':'light');};if(localStorage.getItem('avmTheme')==='dark')document.body.classList.add('dark');try{S.history=JSON.parse(localStorage.getItem('avmHistory')||'[]')}catch{}db();live();
