const $=id=>document.getElementById(id), N=id=>Number($(id)?.value||0)||0, M=n=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const S={db:[],history:[],v:{},c:{},margin:0,roi:15};
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='result')result();if(id==='history')history();}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function read(){S.v={brand:$('brand').value,model:$('model').value,year:N('year'),trim:$('trim').value,traction:$('traction').value,country:$('country').value,mileage:N('mileage'),zipOrigin:$('zipOrigin').value,zipDest:$('zipDest').value,platform:$('platform').value,lot:$('lot').value,market:N('market')};S.c={bid:N('bid'),auctionFee:N('auctionFee'),inland:N('inland'),docs:N('docs'),repairMiami:N('repairMiami'),broker:N('broker'),honorarios:N('honorarios'),freight:N('freight'),customs:N('customs'),dispatch:N('dispatch'),fx:N('fx')||60,repairRD:N('repairRD')};}
function calc(){read();let c=S.c,fob=c.bid+c.auctionFee+c.inland+c.docs+c.repairMiami+c.broker+c.honorarios,disp=fob+c.freight+c.dispatch+c.customs/c.fx,landed=disp+c.repairRD/c.fx;return{fob,disp,landed}}
function live(){let x=calc();$('fob').textContent=M(x.fob);$('dispatchOut').textContent=M(x.disp);$('landed').textContent=M(x.landed)}
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',live));
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim()};function spec(s){let o={};String(s||'').split('||').forEach(p=>{let a=p.split(':');if(a.length>1)o[norm(a[0])]=a.slice(1).join(':').trim()});return o};function te(a,b){a=norm(a).replace(/[^A-Z0-9]/g,'');b=norm(b).replace(/[^A-Z0-9]/g,'');let e=x=>['AWD','4WD','4X4'].includes(x)?'AWD':(['FWD','RWD','4X2','2WD'].includes(x)?x:x);return e(a)===e(b)}
function matches(){read();return S.db.filter(r=>norm(r.Marca)===norm(S.v.brand)&&norm(r.Modelo)===norm(S.v.model)&&Number(r.Año)===S.v.year).map(r=>{let p=spec(r.Especificacion),score=(S.v.trim&&norm(p.SERIE||'').includes(norm(S.v.trim))?50:0)+(S.v.traction&&te(S.v.traction,p.TRACCION)?35:0)+(S.v.country&&norm(S.v.country)===norm(r.Pais)?10:0);return{r,p,score}}).sort((a,b)=>b.score-a.score)}
function applyMatch(){let a=matches();if(!a.length){$('match').textContent='Sin coincidencia segura';$('matchbox').textContent='No se encontró coincidencia exacta por marca + modelo + año. No se cambia el año automáticamente.';return}let x=a[0],v=parseFloat(String(x.r.Valor||'').replace(/[$,]/g,''))||0;if(v){$('market').value=v;S.v.market=v}if(!$('trim').value&&x.p.SERIE)$('trim').value=x.p.SERIE;if(!$('traction').value&&x.p.TRACCION)$('traction').value=x.p.TRACCION;$('match').textContent='Coincidencia encontrada';$('matchbox').innerHTML='<b>'+x.r.Marca+' '+x.r.Modelo+' '+x.r.Año+'</b> · '+(x.p.SERIE||'')+' · '+(x.p.TRACCION||'')+' · Valor '+M(v)}
function csv(t){let lines=t.split(/\r?\n/),h=lines.shift().split(','),out=[];for(let l of lines){let v=[],q=false,c='';for(let ch of l){if(ch==='"')q=!q;else if(ch===','&&!q){v.push(c);c=''}else c+=ch}v.push(c);let o={};h.forEach((k,i)=>o[k.trim()]=String(v[i]??'').replace(/^"|"$/g,''));if(o.Marca)out.push(o)}return out}
async function db(){try{let r=await fetch(encodeURI('Base de Datos Valores Vehiculos 2026 - 2027.csv'));S.db=csv(await r.text());$('dbStatus').textContent=S.db.length.toLocaleString()+' registros';applyMatch();renderDB()}catch(e){$('dbStatus').textContent='Abrir desde servidor/GitHub Pages';}}
function renderDB(){let q=norm($('dbSearch').value),a=S.db.filter(r=>[r.Marca,r.Modelo,r.Año,r.Especificacion,r.Pais].some(x=>norm(x).includes(q))).slice(0,40);$('dbResults').innerHTML=a.map(r=>{let p=spec(r.Especificacion);return '<div class="dbitem"><div><b>'+r.Marca+' '+r.Modelo+' '+r.Año+'</b><br><span>'+(p.SERIE||'')+' · '+(p.TRACCION||'')+' · '+(r.Pais||'')+'</span></div><b>'+r.Valor+'</b></div>'}).join('')||'<p>Sin resultados.</p>'}
$('dbSearch').oninput=renderDB;
async function vin(){let v=$('vin').value.trim().toUpperCase();if(v.length!==17){$('vmsg').textContent='VIN debe tener 17 caracteres';return}try{let r=await fetch('https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/'+encodeURIComponent(v)+'?format=json'),d=(await r.json()).Results?.[0]||{};$('brand').value=d.Make||'';$('model').value=d.Model||'';$('year').value=d.ModelYear||'';$('traction').value=['AWD','FWD','RWD','4WD'].includes(d.DriveType)?d.DriveType:'';$('vmsg').textContent=d.Make?'Datos VIN recibidos; trim/valor se cruzan con la base.':'Sin datos útiles';applyMatch()}catch(e){$('vmsg').textContent='No fue posible consultar el VIN ahora.'}}
$('decode').onclick=vin;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('vinbox').classList.toggle('hidden',b.dataset.mode!=='vin')});
function result(){let x=calc(),market=N('market'),fixed=S.c.auctionFee+S.c.inland+S.c.docs+S.c.repairMiami+S.c.broker+S.c.honorarios+S.c.freight+S.c.dispatch+S.c.customs/S.c.fx+S.c.repairRD/S.c.fx,mb=market-fixed-S.margin,rb=(market-fixed)/(1+S.roi/100),max=Math.max(0,Math.min(mb,rb)),ideal=max*.93,risk=max*.98,sale=N('sale')||market,mar=sale-x.landed,roi=x.landed?mar/x.landed*100:0;$('ideal').textContent=M(ideal);$('max').textContent=M(max);$('risk').textContent=M(risk);$('title').textContent=(S.v.brand+' '+S.v.model+' '+S.v.year+' '+S.v.trim).replace(/\s+/g,' ').trim()||'Vehículo';$('meta').textContent=(S.v.traction||'—')+' · '+(S.v.platform||'—')+' · '+(S.v.mileage||0).toLocaleString()+' mi';$('margin').textContent=M(mar);$('roi').textContent=roi.toFixed(1)+'%';let rows=[['Puja',S.c.bid],['Auction Fee',S.c.auctionFee],['Inland',S.c.inland],['Documentación',S.c.docs],['Reparación Miami',S.c.repairMiami],['Broker',S.c.broker],['Honorarios',S.c.honorarios],['Flete',S.c.freight],['Despacho RD',S.c.dispatch],['Aduanas / DGA',S.c.customs/S.c.fx],['Landed',x.landed]];$('rows').innerHTML=rows.map(r=>'<div class="row"><span>'+r[0]+'</span><b>'+M(r[1])+'</b></div>').join('')}
$('nextCosts').onclick=()=>{applyMatch();page('costs')};$('nextResult').onclick=()=>{live();page('result')};$('sale').oninput=result;
function history(){let a=S.history;$('historyList').innerHTML=a.length?a.map(x=>'<div class="dbitem"><div><b>'+x.v.brand+' '+x.v.model+' '+x.v.year+'</b><br><span>'+x.date+'</span></div><b>'+x.max+'</b></div>').join(''):'Aún no hay operaciones.'}
$('save').onclick=()=>{read();result();S.history.unshift({date:new Date().toLocaleString(),v:{...S.v},max:$('max').textContent});localStorage.setItem('avmHistory',JSON.stringify(S.history));page('history')};$('new').onclick=()=>location.reload();
$('defaults').onclick=()=>{['bid','auctionFee','inland'].forEach(x=>$(x).value=0);$('docs').value=675;$('repairMiami').value=950;$('broker').value=250;$('honorarios').value=0;$('freight').value=910;$('customs').value=0;$('dispatch').value=465;$('fx').value=60;$('repairRD').value=0;live()};
$('saveSettings').onclick=()=>{let v={broker:N('setBroker'),docs:N('setDocs'),repair:N('setRepair'),freight:N('setFreight'),dispatch:N('setDispatch'),fx:N('setFx'),margin:N('setMargin'),roi:N('setROI'),zip:$('setZip').value};S.margin=v.margin;S.roi=v.roi;$('broker').value=v.broker;$('docs').value=v.docs;$('repairMiami').value=v.repair;$('freight').value=v.freight;$('dispatch').value=v.dispatch;$('fx').value=v.fx;$('zipDest').value=v.zip;localStorage.setItem('avmSettings',JSON.stringify(v));live()};
$('analyze').onclick=()=>{let q=$('quick').value.toUpperCase(),y=q.match(/20\d{2}/),z=q.match(/\b\d{5}\b/g),p=q.match(/(?:COMPRA|PUJA|BID)\s*\$?\s*([\d,.]+)/i);if(y)$('year').value=y[0];if(z){$('zipOrigin').value=z[0];if(z[1])$('zipDest').value=z[1]}if(p)$('bid').value=p[1].replace(/,/g,'');['AWD','FWD','4WD','4X4','RWD','4X2'].forEach(t=>{if(q.includes(t))$('traction').value=t});['TOYOTA','HYUNDAI','KIA','HONDA','MAZDA','FORD','CHEVROLET','JEEP','ACURA','NISSAN','LEXUS'].forEach(b=>{if(q.includes(b))$('brand').value=b[0]+b.slice(1).toLowerCase()});['RAV4','TUCSON','SPORTAGE','CRV','CX-5','SANTA FE','HIGHLANDER','MDX','SILVERADO','MUSTANG'].forEach(m=>{if(q.includes(m))$('model').value=m});applyMatch();page('vehicle')};
$('theme').onclick=()=>document.body.classList.toggle('dark');try{S.history=JSON.parse(localStorage.getItem('avmHistory')||'[]')}catch{}db();live();
